{% set name = "opentelemetry-instrumentation-sqlite3" %}
{% set version = "0.42b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_sqlite3-{{ version }}.tar.gz
  sha256: 5d93199509d520edf0dd7c1c6f39cf59af1439f7a3d0f6c65f4744a525b57195

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-dbapi ==0.42b0
    - opentelemetry-instrumentation ==0.42b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-test-utils ==0.42b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-sqlite3
  summary: OpenTelemetry SQLite3 instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
